### ISSUE TITLE
Add chromium to image so we can generate PDF files

### ISSUE THREAD

**Issue by gromain** [SamuelAllain/docker-garradin#1]
With the current image setup, there is an error when trying to generate a PDF file from Garradin.
```
LogicException
Aucun programme de création de PDF trouvé, merci d'en installer un : https://fossil.kd2.org/garradin/wiki?name=Configuration
in .../include/lib/Garradin/Utils.php:1024

1020            }
1021
1022            // We still haven't found anything
1023            if (!$cmd) {
1024                throw new \LogicException('Aucun programme de création de PDF trouvé, merci d\'en installer un : https://fossil.kd2.org/garradin/wiki?name=Configuration');
1025            }
1026        }
1027
1028        switch ($cmd) {
```

According to the [documentation](https://fossil.kd2.org/garradin/wiki?name=Configuration), there are several ways to solve this issue. I think installing `chromium` to the image would be the easiest way to solve this in this image (since setting up [Prince](https://www.princexml.com/doc/installing/#installing-prince-on-linuxfreebsd) in Alpine is a pain in the ass as it's not packaged, also Prince is not libre software).

**Comment by gromain** [comment]
Also, the DOMpdf extension needs the `php-zip` module. If this can be added so this extension can work too.

```
    Cette extension nécessite l'installation du module PHP zip (apt install php-zip).
```

This may not be needed once `chromium` is there though...

**Comment by gromain** [comment]
`chromium` doesn't help for generating pdf for some unknown reason. Installing `php-zip` and DOMpdf extension work though.

**Comment by SamuelAllain** [comment]
php81-zip added
