### ISSUE TITLE
Add in README a way to add load extension in the created volume

### ISSUE THREAD

**Issue by gromain** [SamuelAllain/docker-garradin#2]
Once the container is created with a volume attached, we can get into this volume from the container itself with `sudo docker exec -it ga sh`.

This allows the download of the extensions archive in the `data/plugins` folder. Extensions can be downloaded from the [dedicated repository](https://fossil.kd2.org/garradin-plugins/index).

For example:
```
cd /var/www/garradin/data/plugins/
wget https://fossil.kd2.org/garradin-plugins/uv/dompdf.tar.gz
wget https://fossil.kd2.org/garradin-plugins/uv/taima.tar.gz
wget https://fossil.kd2.org/garradin-plugins/uv/helloasso.tar.gz
```

**Comment by SamuelAllain** [comment]
I downloaded all plugins in the docker image so that it is quicker for everybody and I put something in the README too. Thanks !
