### ISSUE TITLE
mysqli n'est pas nécessaire

### ISSUE THREAD

**Issue by bohwaz** [SamuelAllain/docker-garradin#5]
https://github.com/SamuelAllain/docker-garradin/blob/37d88faac7708e8a12b67ee1655c337cbbf6e158/Dockerfile#L24

Vu que mysql n'est pas utilisé :)

**Comment by bohwaz** [comment]
De même pour  php81-pdo_sqlite qui n'est pas utilisé.

**Comment by SamuelAllain** [comment]
Ok merci
